image: mcr.microsoft.com/playwright:focal

tasks:
  - name: Dev Server
    init: npm ci
    command: npm run dev

ports:
  - name: Dev Server
    port: 5173
    onOpen: open-preview

vscode:
  extensions:
    - lokalise.i18n-ally
    - svelte.svelte-vscode
