name: Bump Package Version

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: polygon-software/npm-version-date@master
        with:
          schema: 'V.yyyyMMdd.P'
          V: '1'
          increase-patch: true
      - uses: EndBug/add-and-commit@v8
        with:
          default_author: github_actions
